# fly.toml app configuration file generated for maexpeditionsreact on 2023-04-26T14:01:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maexpeditionsreact"
primary_region = "mia"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = [80]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ips]]
    ip = "66.51.122.88"
    type = "v4"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

    [[services.ports.inbound]]
      port = 80
